### PR TITLE
Rework the module

### PR DESCRIPTION
**Pull request by dmitryilyin**
- Massive refactoring
- Adding a lot of new features

### CODE REVIEW

**Comment by Ziaunys** [comment]
Hey. Just wanted to let you know that I'm gradually reviewing this PR. So far this looks amazing. I really appreciate all this work! The only problem I can see so far is that your name isn't at the top of the CONTRIBUTORS file. :smile:

**Comment by Ziaunys** [comment]
Since the tests are passing, I'm actually willing to merge this now. I have no objections to the design or functionality these changes provide.

**Comment by dmitryilyin** [comment]
Hi!

Thanks for your support. I hope you'll merge it soon.
- Is it possible for me to receive the rights to commit into this repository?
- Can I add more modules? I have Marathon and Mesos DNS friends for this module.

**Comment by Ziaunys** [comment]
+1 I'll merge it now.

I can't give you direct commit access right now, but I'm usually much faster at reviewing PR's. For modules under the puppetlabs namespace we normally require some amount of review anyways.

I actually have a skeleton module for Marathon in the puppetlabs account that I made as a private repo because I hadn't made any contributions to it. I can go ahead and make that public so you can open a PR against it.  We currently don't have a module for Mesos DNS under the puppetlabs account, but it seems like it would be appropriate as a separate module which could be under your GitHub account.

**Comment by Ziaunys** [comment]
The repo is now public:
https://github.com/puppetlabs/puppetlabs-marathon

**Pull request merged**
